/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.eshop;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Collection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.vandeseer.easytable.TableDrawer;
import org.vandeseer.easytable.settings.HorizontalAlignment;
import org.vandeseer.easytable.structure.Row;
import org.vandeseer.easytable.structure.Table;
import org.vandeseer.easytable.structure.Table.TableBuilder;
import org.vandeseer.easytable.structure.cell.TextCell;
import com.mycompany.eshop.dbHandler;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Thanasis
 */
public class OrderDetails extends javax.swing.JFrame {
    dbHandler db=new dbHandler();
    /**
     * Creates new form OrderDetails
     */
    Orders ord = new Orders();
    List<Product> _products = new ArrayList<Product>();

    
    public OrderDetails() {
        initComponents();
        
    }
    public void setOrder(Orders ord){
        this.ord=ord;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Barcode", "Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Complete Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addGap(163, 163, 163)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            jLabel1.setText("Order ID: "+this.ord.getOrderID());
            jLabel2.setText("Customer: "+this.ord.getCustomer());
            label1.setText("Date : "+this.ord.getDate());
            TableHandler();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OrderDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private Table createHeader() {
          final TableBuilder tableBuilder0 = Table.builder()
                        .addColumnsOfWidth(150,250,250)
                        .padding(2)
                        .addRow(Row.builder()
                                .add(TextCell.builder().text("Order ID: "+ord.getOrderID()).borderWidth(0).backgroundColor(Color.WHITE).build())
                                .add(TextCell.builder().text("Customer Name: "+ord.getCustomer()).borderWidth(0).backgroundColor(Color.WHITE).build())
                                .add(TextCell.builder().text("Order Date: "+ord.getDate()).borderWidth(0).backgroundColor(Color.WHITE).build())
                                .build());
          return tableBuilder0.build();
    }
    private Table createTable(Orders ord) throws SQLException{
        final TableBuilder tableBuilder = Table.builder()
                            .addColumnsOfWidth(200,100,100,100);

                    
                            tableBuilder.addRow(Row.builder()
                                .add(TextCell.builder().text("Product Name").borderWidth(1).backgroundColor(Color.WHITE).build())
                                .add(TextCell.builder().text("Barcode").borderWidth(1).backgroundColor(Color.WHITE).build())
                                .add(TextCell.builder().text("Price").borderWidth(1).backgroundColor(Color.WHITE).build())
                                .add(TextCell.builder().text("Amount").borderWidth(1).backgroundColor(Color.WHITE).build())
                                .build());
                    float total=0;
                    for(int i=0;i<_products.size();i++){
                        total+=_products.get(i).getAmount()*_products.get(i).getPrice();
                        tableBuilder.addRow(Row.builder()
                        .add(TextCell.builder().text(_products.get(i).getName()+"").borderWidth(1).build())
                        .add(TextCell.builder().text(_products.get(i).getBarcode()+"").borderWidth(1).build())
                        .add(TextCell.builder().text( _products.get(i).getPrice()+" €").borderWidth(1).build())
                        .add(TextCell.builder().text(_products.get(i).getAmount()+"").borderWidth(1).borderWidth(1).build())
                        .backgroundColor(Color.WHITE)
                        .build());
                    }
                    tableBuilder.addRow(Row.builder()
                        .add(TextCell.builder().text("Total:").borderWidth(0).build())
                        .add(TextCell.builder().text("").borderWidth(0).build())
                        .add(TextCell.builder().text("").borderWidth(0).build())
                        .add(TextCell.builder().text(total+"€").borderWidth(1).borderWidth(1).build())
                        .backgroundColor(Color.WHITE)
                        .build());
         return tableBuilder.build();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int res=db.OrderSetComplete(ord.getOrderID());
            if(res>0){
                try {
                    TestUtils.createAndSaveDocumentWithTables("../"+ord.getOrderID()+"Order_."+ord.getDate()+".pdf", createHeader(),createTable(ord));
                    TableHandler();
                } catch (IOException ex) {
                    Logger.getLogger(OrderDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
                db.UpdateProductsAfterOrderComplete(_products);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void TableHandler() throws SQLException{
        System.out.println("Eimai edo "+ ord.getOrderID());
        _products = db.getProductsByOrderID(ord.getOrderID());
        
        
        if(jTable1.getModel().getRowCount()!=0){
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
        }
        
        String ordStr[]=new String[ord.getProductList().size()];
        DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
        
        for(int i=0;i<_products.size();i++){
            Product p = _products.get(i);
//            System.out.println(p.getProductString());
            tblModel.addRow(p.getProductForOrderString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
